### ISSUE TITLE
Slider not displayed

### ISSUE THREAD

**Issue by deepentim** [mauricius/ProcessSlider#1]
Even following all steps, the slider is not displayed on the requested page. Save & Test also troubles. It works on Test Results after I double click in Save & Test. I am stuck from last 3 days.

![004](https://cloud.githubusercontent.com/assets/14071397/10951141/de5a6caa-8363-11e5-8cae-22f24329fe7f.png)

![003](https://cloud.githubusercontent.com/assets/14071397/10951142/de5b6d9e-8363-11e5-9e79-a11a3f1f411e.png)

**Comment by mauricius** [comment]
I think I'm going to need a little bit more information than that. Which PW version are you using? Can you show me the PHP code you're using to include the slider and the HTML code of your page, where the slider is supposed to be showing?

**Comment by deepentim** [comment]
I am using ProcessWire 2.6.1. I did not find a way to add PHP/HTML code to add slider. Just I added a field created for Slider to the respective page. As on the first screenshot above.

**Comment by mauricius** [comment]
Please follow the instructions on the MarkupSlider section at this link [https://github.com/mauricius/ProcessSlider#api-markupslider](https://github.com/mauricius/ProcessSlider#api-markupslider) to add the slider to your page.

**Comment by deepentim** [comment]
I created a template `slider.php`. Then I add field `Slider`. 
In the page `slider.php`, i coded as:

``` php
<div id="bodycopy">
<h1><?php echo $page->heading; ?></h1>
<?php
$slider = $modules->get('MarkupSlider');

echo $slider->render($page->get('slider'), $includeScript = true, $options = array())
;?></div>
```

Then I got error when loading the site.
![error](https://cloud.githubusercontent.com/assets/14071397/11117525/9b100aa4-8962-11e5-90a0-e76672882eb3.PNG)

**Comment by mauricius** [comment]
The field that stores the slider clearly is not called `slider`. ProcessWire is trying to get that field from your page, but you can see in the error line #0 that this field is `NULL` so the module doesn't know how to render it. Check in your template and use the correct name.

**Comment by deepentim** [comment]
That issue fixed. But the slider appears on top of the page. Wherever I put the code, it appears above navigation menu.
 My code is
```php

<div id="container">
<?php
$slider = $modules->get('MarkupSlider');

echo $slider->render($page->get('Slider'), $includeScript = true, $options = array());
;?>
</div>
![slider](https://cloud.githubusercontent.com/assets/14071397/11122009/2945b9ea-8981-11e5-8023-aeb5e5755978.PNG)

**Comment by deepentim** [comment]
That issue fixed. But the slider appears top of the page while  want it to appear below navigation bar. Wherever I put the code it appears above nav bar.
```php  
<div id="container">
<?php
$slider = $modules->get('MarkupSlider');
echo $slider->render($page->get('Slider'), $includeScript = true, $options = array());
;?>
</div>

![Slider](https://cloud.githubusercontent.com/assets/14071397/11122082/8c902e40-8981-11e5-8afc-1007a55f7386.PNG)

**Comment by deepentim** [comment]
That issue fixed. But the slider appears top of the page while want it to appear below navigation bar. Wherever I put the code it appears above nav bar.

```php
<div id="container">
<?php
$slider = $modules->get('MarkupSlider');
echo $slider->render($page->get('Slider'), $includeScript = true, $options = array());
;?>
</div>
![Slider on top] (https://cloud.githubusercontent.com/assets/14071397/11122137/e78154fa-8981-11e5-8dbd-90852e5dbbac.PNG)

**Comment by deepentim** [comment]
That issue fixed. But the slider appears top of the page while want it to appear below navigation bar. Wherever I put the code it appears above nav bar.

``` php
<div id="container">
<?php
$slider = $modules->get('MarkupSlider');
echo $slider->render($page->get('Slider'), $includeScript = true, $options = array());
;?>
</div>
```

![slider](https://cloud.githubusercontent.com/assets/14071397/11122446/66c79ad4-8983-11e5-8d0a-da9903ac1498.PNG)

**Comment by mauricius** [comment]
You have to define a container for the slider and work on your CSS rules for positioning it. This is not an issue of the module therefore I'm closing the thread.
